# This is the configuration used to check the rubocop source code.

Rails:
  Enabled: true

AllCops:
  Exclude:
    - spec/support/spec_helper.rb
    - spec/rails_helper.rb
    - db/**/*
    - docs/**/*
    - config/**/*
    - bin/**/*
    - script/**/*
    - node_modules/**/*
    - Gemfile
    - test/**/*
    - vendor/**/*

HasAndBelongsToMany:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/LineLength:
  Max: 99

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Rails/ApplicationController:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# rubocop-rspec custom configurations

require:
  - rubocop-rspec
  - rubocop-rails

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/ExampleLength:
  Exclude:

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

FactoryBot/AttributeDefinedStatically:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
